[package]
name = "snippet-agent"
version = "0.1.2"
edition = "2024"
description = "Codebase parsing tool. It aggregates code (i.e. RAG) as an input to LLMs"
license = "MIT"
readme = "README.org"
repository = "https://github.com/pramatias/snippet-agent"
keywords = ["parser", "cli", "rag"]

[workspace]
members = [
    "snippet-agent-syntax-queries",
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "4.5.23"
log = "0.4"
ctrlc = "3.4.5"
anyhow = "1.0.95"
clap-verbosity-flag = "3.0.2"
console = "0.16.2"
env_logger = "0.11.8"
tempfile = "3.24.0"
regex = "1.12.2"
duct = "1.1.1"
thiserror = "2.0.17"
walkdir = "2.5.0"
syntax_queries = { package = "snippet-agent-syntax-queries", path = "snippet-agent-syntax-queries", version = "0.1.2" }

directories = "6.0.0"
indextree = "4.7.4"

[dev-dependencies]
tempfile = "3.10"
