[package]
name = "snippet-agent-syntax-queries"
version = "0.1.2"
edition = "2024"
description = "Tree-sitter based queries and utilities for snippet-agent (syntax queries)."
license = "MIT"
readme = "README.org"
repository = "https://github.com/pramatias/snippet-agent"
keywords = ["tree-sitter", "parser", "rag"]

[dependencies]
log = "0.4.29"
serde = { version = "1.0", features = ["derive"] }
tree-sitter = { version = "0.26.3" }
tree-sitter-rust = { version = "0.24.0" }

[build-dependencies]
cc="1"
